app:
  name: react-environment-demo
  version: v1.0.0

namespace:
  name: origin-prod
  labels:
    ns: origin-prod

replicaCount: 2

image:
  repository: rizkypanz/react-environment-demo
  tag: "v1.0.0"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 3000

configmap:
  name: react-environment-demo-origin-prod
  data:
    NODE_ENV: production
    REACT_APP_NODE_ENV: origin-prod
    REACT_APP_VERSION: v1.0.0
