app:
  name: react-environment-demo
  version: v1.0.0

namespace:
  name: origin-dev
  labels:
    ns: origin-dev

replicaCount: 3

image:
  repository: rizkypanz/react-environment-demo
  tag: "v1.0.0"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 3000

configmap:
  name: react-environment-origin-dev
  data:
    NODE_ENV: development
    REACT_APP_NODE_ENV: origin-dev
    REACT_APP_VERSION: v1.0.0
