kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace.name }}
data:
  NODE_ENV: {{ .Values.configmap.data.NODE_ENV }}
  REACT_APP_NODE_ENV: {{ .Values.configmap.data.REACT_APP_NODE_ENV }}
  REACT_APP_VERSION: {{ .Values.configmap.data.REACT_APP_VERSION }}
